export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const SET_CHECKEDOUT_ITEMS = "SET_CHECKEDOUT_ITEMS";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
export const FETCH_ALL_ITEMS_IN_CART = "FETCH_ALL_ITEMS_IN_CART";

